// MyUsbLowerFilter.cpp
//
// Generated by C DriverWizard 3.2.0 (Build 2485)
// Requires DDK Only
// File created on 8/28/2008
//

#include <windows.h>
#include <stdio.h>
#include <tchar.h>
#include <setupapi.h>
#include <newdev.h>
#include "MyUsbLowerFilterDll.h"

BOOL APIENTRY DllMain( HANDLE hModule,
                       DWORD  ul_reason_for_call,
                       LPVOID lpReserved
                     )
{
    switch (ul_reason_for_call)
    {
        case DLL_PROCESS_ATTACH:
        case DLL_THREAD_ATTACH:
        case DLL_THREAD_DETACH:
        case DLL_PROCESS_DETACH:
            break;
    }
    return TRUE;
}

///////////////////////////////////////////////////////////////////////////////////////////////////
// RemoveService
//
// This function removes a service from the registry
//
DWORD RemoveService(LPCTSTR pszFilterName)
{
    DWORD status = ERROR_SUCCESS;

    SC_HANDLE schSCManager = OpenSCManager(
                                    NULL,                   // computer name
                                    NULL,                   // SCM database name
                                    SC_MANAGER_ALL_ACCESS   // access type
                                    );

    if (schSCManager)
    {
        SC_HANDLE schService = OpenService(
                                    schSCManager,       // handle to SCM database
                                    pszFilterName,      // service name
                                    SERVICE_ALL_ACCESS  // access
                                    );

        if (schService)
        {
            status = DeleteService(schService);
            CloseServiceHandle(schService);
        }
        else
        {
            status = GetLastError();
        }

        CloseServiceHandle(schSCManager);
    }
    else
    {
        status = GetLastError();
    }

    return status;
}


///////////////////////////////////////////////////////////////////////////////////////////////////
// AddService
//
// This function adds a service to the registry
//
DWORD AddService(LPCTSTR pszFilterName, LPCTSTR pszServiceBinary)
{
    DWORD status = ERROR_SUCCESS;

    SC_HANDLE schSCManager = OpenSCManager(
                                NULL,                 // computer name
                                NULL,                 // SCM database name
                                SC_MANAGER_ALL_ACCESS // access type
                                );

    if (schSCManager)
    {

        SC_HANDLE schService = CreateService(
                                    schSCManager,          // SCManager database
                                    pszFilterName,         // name of service
                                    pszFilterName,         // name to display
                                    SERVICE_ALL_ACCESS,    // desired access
                                    SERVICE_KERNEL_DRIVER, // service type
                                    SERVICE_DEMAND_START,  // start type
                                    SERVICE_ERROR_NORMAL,  // error control type
                                    pszServiceBinary,      // service's binary
                                    NULL,                  // no load ordering group
                                    NULL,                  // no tag identifier
                                    NULL,                  // no dependencies
                                    NULL,                  // LocalSystem account
                                    NULL                   // no password
                                    );
        if (schService)
        {
            CloseServiceHandle(schService);
        }
        else
        {
            status = GetLastError();
        }

        CloseServiceHandle(schSCManager);
    }
    else
    {
        status = GetLastError();
    }

    return status;
}

///////////////////////////////////////////////////////////////////////////////////////////////////
//  SearchMultiSz
//      This function searches for a substring within a string.
//
//  Arguments:
//      IN  Value
//              string to search
//
//      IN  ValueLength
//              length of the string to search
//
//      IN  SearchString
//              substring used in the search
//
//  Return Value:
//      NULL if string not found; otherwise pointer to next string character
//		just after the search string
//
LPTSTR SearchMultiSz(LPTSTR Value, ULONG ValueLength, LPCTSTR SearchString)
{
    if(ValueLength < _tcslen(SearchString)*sizeof(TCHAR))
        return NULL;

    SIZE_T length = ValueLength - _tcslen(SearchString)*sizeof(TCHAR);
    do
    {
        if (!_tcsicmp(&Value[length/sizeof(TCHAR)], SearchString))
            return &Value[length];

    }
    while(--length);

    return NULL;
}

///////////////////////////////////////////////////////////////////////////////////////////////////
//  Install
//      This function is exported by the dll.  The function installs
//		the WDM filter driver.
//
//  Arguments:
//      None
//
//  Return Value:
//      Status
//
DWORD Install(void)
{
    DWORD status = ERROR_SUCCESS;

		  TCHAR windowsDirectory[MAX_PATH];

    ZeroMemory(windowsDirectory, sizeof(windowsDirectory));

    if (!GetWindowsDirectory(windowsDirectory, sizeof(windowsDirectory)))
    {
        status = GetLastError();
        return status;
    }

    SIZE_T newFileNameLength = _tcslen(windowsDirectory) + _tcslen(_T("\\System32\\Drivers\\")) + _tcslen(_T("MyUsbLowerFilter.sys")) + 1;
    LPTSTR newFileName = new TCHAR[newFileNameLength];
    if (newFileName == NULL)
    {
        status = ERROR_NOT_ENOUGH_MEMORY;
        return status;
    }

    ZeroMemory(newFileName, sizeof(newFileNameLength));

    _tcscpy(newFileName, windowsDirectory);
    _tcscat(newFileName, _T("\\System32\\Drivers\\"));
    _tcscat(newFileName, _T("MyUsbLowerFilter.sys"));

    // Copy the driver file to system32/drivers
    if(!CopyFile(
                _T("MyUsbLowerFilter.sys"),  // name of an existing file
                newFileName,                // name of new file
                FALSE                       // operation if file exists
                ))
    {
        delete newFileName;

        status = GetLastError();
        return status;
    }

    delete newFileName;

    status = AddService(_T("MyUsbLowerFilter"), _T("System32\\Drivers\\MyUsbLowerFilter.sys"));

    if ((status != ERROR_SUCCESS) && (status != ERROR_SERVICE_EXISTS))
    {
        return status;
    }

    HDEVINFO hDevInfo = SetupDiGetClassDevs(NULL, NULL, NULL, DIGCF_ALLCLASSES | DIGCF_PRESENT);
    if (hDevInfo == INVALID_HANDLE_VALUE)
    {
        status = GetLastError();
        return status;
    }

    SP_DEVINFO_DATA devInfoData = {sizeof(SP_DEVINFO_DATA)};
    for (DWORD index = 0; SetupDiEnumDeviceInfo(hDevInfo, index, &devInfoData); ++index)
    {
        TCHAR devDesc[MAX_PATH];
        DWORD nSize = 0;

        if (SetupDiGetDeviceRegistryProperty(
                hDevInfo,
                &devInfoData,
                SPDRP_DEVICEDESC,
                NULL,
                (PBYTE)&devDesc,
                sizeof(devDesc),
                &nSize)
                )
        {
            if (_tcscmp(devDesc, _T("USB 人体学输入设备")) == 0)
            {
                TCHAR filters[MAX_PATH];
                DWORD filtersLength = 0;

                if (SetupDiGetDeviceRegistryProperty(
                        hDevInfo,
                        &devInfoData,
                        SPDRP_LOWERFILTERS,
                        NULL,
                        (PBYTE)filters,
                        sizeof(filters),
                        &filtersLength)
                        )
                {
                    LPTSTR p = SearchMultiSz(filters, filtersLength, _T("MyUsbLowerFilter"));

                    if (p == NULL)
                    {
                        _tcscpy(&filters[filtersLength/sizeof(TCHAR) - 1], _T("MyUsbLowerFilter"));
                        filtersLength += (DWORD)_tcslen(_T("MyUsbLowerFilter"))*sizeof(TCHAR);
                        filters[filtersLength/sizeof(TCHAR)] = 0;
                        filters[filtersLength/sizeof(TCHAR) + 1] = 0;

                        if (!SetupDiSetDeviceRegistryProperty(
                                hDevInfo,
                                &devInfoData,
                                SPDRP_LOWERFILTERS,
                                (PBYTE)filters,
                                filtersLength + sizeof(TCHAR))
                                )
                        {
                            status = GetLastError();
                        }
                    }
                }
                else
                {
                    status = GetLastError();

                    if (status == ERROR_INVALID_DATA)
                    {
                        status = ERROR_SUCCESS;

                        _tcscpy(filters, _T("MyUsbLowerFilter"));
                        filtersLength = (DWORD)_tcslen(_T("MyUsbLowerFilter"))*sizeof(TCHAR);
                        filters[filtersLength/sizeof(TCHAR)] = 0;
                        filters[filtersLength/sizeof(TCHAR) + 1] = 0;

                        if (!SetupDiSetDeviceRegistryProperty(
                                hDevInfo,
                                &devInfoData,
                                SPDRP_LOWERFILTERS,
                                (PBYTE)filters,
                                filtersLength + 2*sizeof(TCHAR))
                                )
                        {
                            status = GetLastError();
                        }
                    }
                }
            }
        }
    }

    SetupDiDestroyDeviceInfoList(hDevInfo);

    return status;
}

///////////////////////////////////////////////////////////////////////////////////////////////////
//  Uninstall
//      This function is exported by the dll.  The function uninstalls
//		the WDM filter driver.
//
//  Arguments:
//      None
//
//  Return Value:
//      Status
//
DWORD Uninstall(void)
{
    DWORD status = ERROR_SUCCESS;

    HDEVINFO hDevInfo = SetupDiGetClassDevs(NULL, NULL, NULL, DIGCF_ALLCLASSES | DIGCF_PRESENT);
    if (hDevInfo == INVALID_HANDLE_VALUE)
    {
        status = GetLastError();
        return status;
    }

    SP_DEVINFO_DATA devInfoData = {sizeof(SP_DEVINFO_DATA)};
    for (DWORD index = 0; SetupDiEnumDeviceInfo(hDevInfo, index, &devInfoData); ++index)
    {
        TCHAR devDesc[MAX_PATH];
        DWORD nSize = 0;

        if (SetupDiGetDeviceRegistryProperty(
                hDevInfo,
                &devInfoData,
                SPDRP_DEVICEDESC,
                NULL,
                (PBYTE)&devDesc,
                sizeof(devDesc),
                &nSize)
                )
        {
            if (_tcscmp(devDesc, _T("USB 人体学输入设备")) == 0)
            {
                TCHAR filters[MAX_PATH];
                DWORD filtersLength = 0;

                if (SetupDiGetDeviceRegistryProperty(
                        hDevInfo,
                        &devInfoData,
                        SPDRP_LOWERFILTERS,
                        NULL,
                        (PBYTE)filters,
                        sizeof(filters),
                        &filtersLength)
                        )
                {
                    LPTSTR p = SearchMultiSz(filters, filtersLength, _T("MyUsbLowerFilter"));

                    if (p != NULL)
                    {
                        MoveMemory(
                            p,
                            p + _tcslen(_T("MyUsbLowerFilter"))*sizeof(TCHAR) + sizeof(TCHAR),
                            filtersLength - (p - filters)*sizeof(TCHAR) - _tcslen(_T("MyUsbLowerFilter"))*sizeof(TCHAR) - sizeof(TCHAR)
                            );

                        filtersLength -= (DWORD)(_tcslen(_T("MyUsbLowerFilter")) + 1)*sizeof(TCHAR);

                        if (!SetupDiSetDeviceRegistryProperty(
                                hDevInfo,
                                &devInfoData,
                                SPDRP_LOWERFILTERS,
                                (PBYTE)filters,
                                filtersLength)
                                )
                        {
                            status = GetLastError();
                        }
                    }
                }
                else
                {
                    status = GetLastError();
                }
            }
        }
    }

    SetupDiDestroyDeviceInfoList(hDevInfo);

    status = RemoveService(_T("MyUsbLowerFilter"));

    return status;
}

