// MyUsbLowerFilter.h
//
// Generated by C DriverWizard 3.2.0 (Build 2485)
// Requires DDK Only
// File created on 8/28/2008
//
#ifndef __MYUSBLOWERFILTERDLL_H__
#define __MYUSBLOWERFILTERDLL_H__

extern "C"
{

DWORD Install(void);
DWORD Uninstall(void);

}

#endif // __MYUSBLOWERFILTERDLL_H__
