// function.h
//
// Generated by DriverWizard 3.2.0 (Build 2485)
// Requires DDK and DriverWorks
// File created on 8/22/2008
//
// This include file specifies the set of request handlers that the
// driver implements.  This controls which driver functions are enabled.
//
#ifndef __FUNCTION_H__
#define __FUNCTION_H__

#define DRIVER_FUNCTION_CREATE
#define DRIVER_FUNCTION_CLOSE
#define DRIVER_FUNCTION_READ
#define DRIVER_FUNCTION_WRITE
#define DRIVER_FUNCTION_DEVICE_CONTROL
#define DRIVER_FUNCTION_CLEANUP
#define DRIVER_FUNCTION_ADD_DEVICE
#define DRIVER_FUNCTION_PNP
#define DRIVER_FUNCTION_POWER
#define DRIVER_FUNCTION_SYSTEM_CONTROL
#define DRIVER_FUNCTION_UNLOAD

#endif // __FUNCTION_H__
