/********************************** (C) COPYRIGHT ******************************
* File Name          : ENGLISH.H
* Author             : WCH
* Version            : V1.0
* Date               : 2013/11/15
* Description        : define for EXTEST.C
*******************************************************************************/



/******************************************************************************/
#ifndef __EXTEST_H
#define __EXTEST_H	 




void EX_TEST( void );


		  				    
#endif
