/********************************** (C) COPYRIGHT ******************************
* File Name          : TP.H
* Author             : WCH
* Version            : V1.0
* Date               : 2013/11/15
* Description        : define for EXTEST.C
*******************************************************************************/



/******************************************************************************/
#ifndef __TP_H
#define __TP_H	 


#define X_min 100		 //TP测试范围常量定义
#define X_max 0x07AE
#define Y_min 180
#define Y_max 0x0759

#define X_divider  0x076b
#define Y_divider  0x06b6




extern void TP_DrawLine_TEST(void);

#endif

