
	// Usb.idl : IDL source for Usb.exe
//
// This file will be processed by the MIDL tool to
// produce the type library (Usb.tlb) and marshalling code.
import "oaidl.idl";
import "ocidl.idl";
[
	uuid(F48BC036-1A34-4167-AB7F-714F9B169E78),
	version(1.0),
	helpstring("Usb 1.0 Type Library")
]
library UsbLib
{
	importlib("stdole32.tlb");
	importlib("stdole2.tlb");
};

	