/********************************** (C) COPYRIGHT ******************************
* File Name          : CHAR.H
* Author             : WCH
* Version            : V1.0
* Date               : 2013/11/15
* Description        : define for ENGLISH.C
*******************************************************************************/



/******************************************************************************/
/* 头文件包含 */
#ifndef __ENGLISH_H
#define __ENGLISH_H	 




void TEST_CHAR( void );


		  				    
#endif
