//
// Computer00UsbApp.h
//
// Generated by C DriverWizard 3.2.0 (Build 2485)
// Requires DDK Only
// File created on 8/22/2008
//
#include <windows.h>
#include <stdio.h>
#include <stdlib.h>
#include <process.h>
#include <commctrl.h>
#include <tchar.h>
#include <setupapi.h>
#include <initguid.h>
#include <winioctl.h>
#include <process.h>
#include <assert.h>
#include <dbt.h>
#include "resource.h"

#include "..\intrface.h"

#define MAX_STRING_LENGTH       500

typedef VOID (*COMPUTER00USB_IO_CALLBACK)(PVOID Context);

// Structure used to store I/O information for delayed
// processing of overlapped requests
typedef struct _COMPUTER00USB_LIST_ITEM
{
    struct _COMPUTER00USB_LIST_ITEM*  Next;
    struct _COMPUTER00USB_LIST_ITEM*  Previous;
    OVERLAPPED                  IoOverlapped;
    PCHAR                       InBuffer;
    PCHAR                       OutBuffer;
    ULONG                       InSize;
    ULONG                       OutSize;
    ULONG                       ReturnLength;
    ULONG                       Error;
    COMPUTER00USB_IO_CALLBACK         Callback;
} COMPUTER00USB_LIST_ITEM, *PCOMPUTER00USB_LIST_ITEM;

extern HANDLE           g_hDevice;
extern COMPUTER00USB_LIST_ITEM    g_IoList;
extern CRITICAL_SECTION g_IoListLock;

ULONG Computer00UsbExecuteIo(HWND hDlg);
UINT __stdcall Computer00UsbIoCompletionThread(PVOID Context);
VOID Computer00UsbOutputText(LPCTSTR Format, ...);
VOID Computer00UsbOutputBuffer(PVOID Buffer, ULONG Size);

