/******************************************************************
   本程序只供学习使用，未经作者许可，不得用于其它任何用途
			
        欢迎访问我的USB专区：http://group.ednchina.com/93/
        欢迎访问我的blog：   http://www.ednchina.com/blog/computer00
                             http://computer00.21ic.org

        感谢PCB赞助商——电子园： http://bbs.cepark.com/

FAT.h file

作者：电脑圈圈
建立日期: 2008.08.19
修改日期: 2008.08.20
版本：V1.1
版权所有，盗版必究。
Copyright(C) 电脑圈圈 2008-2018
All rights reserved            
*******************************************************************/

#ifndef __FAT_H__
#define __FAT_H__

#include "MyType.h"

extern code uint8 Dbr[];
extern code uint8 Fat[];
extern code uint8 Zeros[];
extern code uint8 TestFileData[];
extern code uint8 RootDir[];

#endif