/******************** (C) COPYRIGHT ********************************************
* File Name          : PRINTF.H
* Author             : MJX
* Version            : V1.30
* Date               : 2016/01/05
* Description        : 串口打印输出控制头文件
*******************************************************************************/

#ifndef	__PRINTF_H__
#define __PRINTF_H__

/* 定义串口打印输出开关 */
#define     MY_DEBUG_PRINTF       1				 				 				/* 常归打印监视开关 */ 	

#endif

